name: macOS

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-arm64:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Brew
      run: brew install autoconf automake
    - name: Autogen
      working-directory: ogg
      run: ./autogen.sh
    - name: Configure
      working-directory: ogg
      run: ./configure
    - name: Make
      working-directory: ogg
      run: make
    - name: Install
      working-directory: ogg
      run: sudo make install
