name: macOS

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-arm64:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build
      working-directory: ogg
      run: |
        mkdir build
        cd build
        cmake -G Xcode ..
        cmake -DCMAKE_BUILD_TYPE=Release --build .
        sudo cmake --install .
