name: macOS

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-arm64:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Brew
      run: brew install autoconf automake
    - name: Build ogg
      working-directory: ogg
      run: |
        mkdir build
        cd build
        cmake -G Xcode -DCMAKE_OSX_DEPLOYMENT_TARGET=14.0 ..
        cmake --build . --config Release
        sudo cmake --install .
    - name: Build vorbis
      working-directory: vorbis
      run: |
        mkdir build
        cd build
        cmake -G Xcode -DCMAKE_OSX_DEPLOYMENT_TARGET=14.0 ..
        cmake --build . --config Release
        sudo cmake --install .
    - name: Build tools
      run: |
        ./autogen.sh
        ./configure LIBS="-liconv"
        make
    - name: Strip
      run: strip -u -r oggenc/oggenc
    - name: Sign
      run: codesign --sign - --timestamp --force oggenc/oggenc

  build-x64:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Brew
      run: brew install autoconf automake
    - name: Build ogg
      working-directory: ogg
      run: |
        mkdir build
        cd build
        cmake -G Xcode -DCMAKE_OSX_DEPLOYMENT_TARGET=13.0 ..
        cmake --build . --config Release
        sudo cmake --install .
    - name: Build vorbis
      working-directory: vorbis
      run: |
        mkdir build
        cd build
        cmake -G Xcode -DCMAKE_OSX_DEPLOYMENT_TARGET=13.0 ..
        cmake --build . --config Release
        sudo cmake --install .
    - name: Build tools
      run: |
        ./autogen.sh
        ./configure LIBS="-liconv"
        make
    - name: Strip
      run: strip -u -r oggenc/oggenc
    - name: Sign
      run: codesign --sign - --timestamp --force oggenc/oggenc
